In [1]:
# Pi structure modification
# ENV_PATH = 'keva_double_station_new_table.dae'
ENV_PATH = 'keva_tower_24_structure_new_table.dae'
# ENV_PATH = 'keva_triple_pi_structure_new_table.dae'

import env_build_helper
from openravepy import *
import numpy as np

env = env_build_helper.load_env(ENV_PATH)
all_planks = env_build_helper.get_structure_planks(env)

basic_pi_planks = all_planks[:2]
print(basic_pi_planks) # Should be plank 1,2 and 3 

[RaveGetEnvironment(1).GetKinBody('plank1'), RaveGetEnvironment(1).GetKinBody('plank2')]


In [4]:
# Remove extra planks and bodies (if any)
for i in env.GetBodies():
    if i not in basic_pi_planks:
        env.RemoveKinBody(i)

basic_pi_planks = env_build_helper.get_structure_planks(env)
for i in basic_pi_planks:
    name = i.GetName()
    tx = i.GetTransform()
    env.RemoveKinBody(i)
    p = env_build_helper.create_plank(env,name,tx)



In [3]:
plank1, tx1 = env_build_helper.get_plank_body_from_num(env,1)
plank2, tx2 = env_build_helper.get_plank_body_from_num(env,2)
# plank3, tx3 = env_build_helper.get_plank_body_from_num(env,3)
fix = np.eye(4)
fix[:3,3] = -tx1[:3,3]
print(tx1)
plank1.SetTransform(np.matmul(fix,tx1))
plank2.SetTransform(np.matmul(fix,tx2))
# plank3.SetTransform(np.matmul(fix,tx3))
################################################################################

[[ 1.00000000e+00 -0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -2.22044605e-16  1.00000000e+00  0.00000000e+00]
 [-0.00000000e+00 -1.00000000e+00 -2.22044605e-16  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [1]:
#Repeating structures:

ENV_PATH = 'NEW/tower_2_plank_structure.dae'
import env_build_helper
from openravepy import *
import numpy as np

env = env_build_helper.load_env(ENV_PATH)
basic_pi_planks = env_build_helper.get_structure_planks(env)

In [2]:
plank1, tx1 = env_build_helper.get_plank_body_from_num(env,1)
print(tx1)

[[ 1.00000000e+00 -0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -2.22044605e-16  1.00000000e+00  0.00000000e+00]
 [-0.00000000e+00 -1.00000000e+00 -2.22044605e-16  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [3]:
no_of_levels = 12
new_planks = []
for i in range(1,no_of_levels):
    for j in basic_pi_planks:
        plank_num = int(j.GetName()[-1])
        tx = j.GetTransform()
        if i % 2 != 0:
            tx[0,3] = np.power(-1,plank_num)*0.04
            tx[1,3] = -0.04
            rot = np.eye(4)
            rot[:3,:3] = rotationMatrixFromAxisAngle([0,-np.pi/2,0])
            tx = np.matmul(tx,rot)
        tx[2,3] += 2*(0.01162 + 0.0001)*i
        name = j.GetName()
        name = name[:-1]+str(int(name[-1])+2*i)
        p = env_build_helper.create_plank(env,name,tx)
        new_planks.append(p)  

In [5]:
for i in new_planks:
    env.RemoveKinBody(i)

In [6]:
env.CheckCollision(env.GetKinBody('plank1'),env.GetKinBody('plank2'))

False

In [12]:
plank, tx = env_build_helper.get_plank_body_from_num(env,3)
rot = np.eye(4)
rot[:3,:3] = rotationMatrixFromAxisAngle([0,np.pi/2,0])
tx = np.matmul(tx,rot)
plank.SetTransform(tx)

In [2]:
plank, tx = env_build_helper.get_plank_body_from_num(env,2)

In [4]:
tx[0:3,3] = [0.00,-0.0800,0.00]

In [5]:
# tx[0,3]+=0.02
plank.SetTransform(tx)

In [3]:
plank.GetTransformPose()

array([ 0.70710678, -0.70710678,  0.        ,  0.        ,  0.        ,
       -0.09      ,  0.        ])

In [18]:
np.power(-1,0)

1